### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by mokhosh** [pacoorozco/gamify-laravel#200]
4 packages seem to be incompatible with PHP 8.
- fzaninotto/faker (we should use fakerphp/faker instead)
- qcod/laravel-imageup (needs pr)
- socialiteproviders/manager (newest version seems to support php 8)
- socialiteproviders/okta (newest version seems to support php 8)

**Comment by pacoorozco** [comment]
Waiting for qcod/laravel-imageup/#54
