### ISSUE TITLE
Get error when creating questions 

### ISSUE THREAD

**Issue by Temian1** [pacoorozco/gamify-laravel#382]
```
SQLSTATE[42000]: Syntax error or access violation: 1055 'nairamar_ga.badges.name' isn't in GROUP BY
SELECT
  `badges`.*
FROM
  `badges`
  INNER JOIN `taggable_taggables` AS `taggable_taggables_scopewithanytags_1` ON `badges`.`id` = `taggable_taggables_scopewithanytags_1`.`taggable_id`
  AND `taggable_taggables_scopewithanytags_1`.`taggable_type` = Gamify \ Models \ Badge
WHERE
  `active` = 1
  AND actuators & 7 > 0
  AND `taggable_taggables_scopewithanytags_1`.`tag_id` IN (2)
  AND `badges`.`deleted_at` IS NULL
GROUP BY
  `badges`.`id`

**Comment by pacoorozco** [comment]
Hi @Temian1 

**Can you provide more context in order to scope the error?**

- When the error was raised? Saving the question?
- Which badges do you have?

**Comment by Temian1** [comment]
I didn't create any badge, I only seed all files and when I Check the admin area badges and levels has already been created

So I tried creating questions it's worked

But I can't edit the question or publish it

**Comment by pacoorozco** [comment]
Yes, It will be good to troubleshoot what's happening.

**Comment by Temian1** [comment]
> Yes, It will be good to troubleshoot what's happening.

Here is the website naijatalks.com

Still the same admin login details

**Comment by pacoorozco** [comment]
I've accessed there and I've been able to create two questions wo/ any error... 

**Are you doing something different?**

**Comment by pacoorozco** [comment]
I've seen the error now... the error is happening when you try to view a question that was created previously, right?

**Comment by pacoorozco** [comment]
I guess the problem is related to [this one](https://stackoverflow.com/questions/41571271/group-by-not-working-laravel). 

In my local environment I'm using **mysql v8**, which is probably using `GROUP BY` differently. **Can you provide the mysql version you're using**?

**Comment by Temian1** [comment]
> an you prov

Yes 

> I've seen the error now... the error is happening when you try to view a question that was created previously, right?

Yeah that's is the issue

**Comment by Temian1** [comment]
> I guess the problem is related to [this one](https://stackoverflow.com/questions/41571271/group-by-not-working-laravel).
> 
> In my local environment I'm using **mysql v8**, which is probably using `GROUP BY` differently. **Can you provide the mysql version you're using**?

Database client version: libmysql - mysqlnd 7.4.32

**Comment by pacoorozco** [comment]
Yes, you're using a version that is not allowing this `GROUP BY` clause. I don't fully understand why mysql v8 (in the docker environment) is working well, but I'm afraid that is because it's configured differently.

So, as a workaround, go to your `config/database.php` and **update `strict` value to `false`**.

```
return [
   'connections' => [
      'mysql' => [
         'strict' => false
       ]
   ]
]
```
